<a href="https://colab.research.google.com/github/Manikanta-23-ai/Machine-Learning-Projects/blob/main/PRACTICE_FOR_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:

base_url = "https://www.airlinequality.com/airline-reviews/british-airways"
pages = 10
page_size = 100

reviews = []

for i in range(1, pages + 1):
    print(f"Scraping page {i}")

    # Create URL to collect links from paginated data.
    url = f"{base_url}/page/{i}/?sortby=post_date%3ADesc&pagesize={page_size}"

    # Collect HTML data from this page.
    response = requests.get(url)

    # Parse content.
    content = response.content
    parsed_content = BeautifulSoup(content, "html.parser")
    for para in parsed_content.find_all("div", {"class": "text_content"}):
        reviews.append(para.get_text())

    print(f"   ---> {len(reviews)} total reviews")

Scraping page 1
   ---> 100 total reviews
Scraping page 2
   ---> 200 total reviews
Scraping page 3
   ---> 300 total reviews
Scraping page 4
   ---> 400 total reviews
Scraping page 5
   ---> 500 total reviews
Scraping page 6
   ---> 600 total reviews
Scraping page 7
   ---> 700 total reviews
Scraping page 8
   ---> 800 total reviews
Scraping page 9
   ---> 900 total reviews
Scraping page 10
   ---> 1000 total reviews

In [ ]:
df = pd.DataFrame()
df["reviews"] = reviews
df.head()

                                             reviews
0  Not Verified |  This recent experience has bee...
1  ✅ Trip Verified |  Well what can I say I thoug...
2  ✅ Trip Verified |  Great flight, and what a ch...
3  ✅ Trip Verified |    I had sworn never again w...
4  ✅ Trip Verified |    Flying business and not a...

In [ ]:
if not os.path.exists(os.path.join(os.getcwd(), "data")):
    os.mkdir("data")

df.to_csv("data/BA_reviews_raw.csv")

df["reviews"] = df["reviews"].str.split("|", expand=True)[1]
df.head()

In [ ]:
import string

def case_and_punctuation_handling(text):
    lower_case_text = text.lower()
    cleaned_text = lower_case_text.translate(str.maketrans("", "", string.punctuation))
    return cleaned_text

df["cleaned_reviews"] = df["reviews"].apply(case_and_punctuation_handling)
df.head()

,reviews,cleaned_reviews
0,Not Verified | This recent experience has bee...,not verified this recent experience has been...
1,✅ Trip Verified | Well what can I say I thoug...,✅ trip verified well what can i say i though...
2,"✅ Trip Verified | Great flight, and what a ch...",✅ trip verified great flight and what a chan...
3,✅ Trip Verified | I had sworn never again w...,✅ trip verified i had sworn never again wi...
4,✅ Trip Verified | Flying business and not a...,✅ trip verified flying business and not ab...

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk  import pos_tag
from nltk.corpus import wordnet
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
# POS tagging dictionary.
nltk.download('punkt')
pos_dict = {"J":wordnet.ADJ, "V":wordnet.VERB, "N":wordnet.NOUN, "R":wordnet.ADV}

def handle_tokenization_stopwords_postags(text):
    # Tokenization.
    tokenized_text = word_tokenize(text)
    # POS-tagging.
    tags = pos_tag(tokenized_text)
    new_text_list = []
    for word, tag in tags:
        # Stopword removal.
        if word not in stopwords.words("english"):
          new_text_list.append(tuple([word, pos_dict.get(tag[0])]))
    return new_text_list
    df["cleaned_reviews"].apply(handle_tokenization_stopwords_postags)
df.head()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

,reviews,cleaned_reviews
0,Not Verified | This recent experience has bee...,not verified this recent experience has been...
1,✅ Trip Verified | Well what can I say I thoug...,✅ trip verified well what can i say i though...
2,"✅ Trip Verified | Great flight, and what a ch...",✅ trip verified great flight and what a chan...
3,✅ Trip Verified | I had sworn never again w...,✅ trip verified i had sworn never again wi...
4,✅ Trip Verified | Flying business and not a...,✅ trip verified flying business and not ab...

In [ ]:
# Obtaining stem-words with Lemmatization.
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

def text_lemmatization(pos_data):
    lemma_rew = " "
    for word, pos in pos_data:
     if not pos:
        lemma = word
        lemma_rew = lemma_rew + " " + lemma
     else:
        lemma = wordnet_lemmatizer.lemmatize(word, pos=pos)
        lemma_rew = lemma_rew + " " + lemma
    return lemma_rew
df["POS_tag.apply(text_lemmatization)
ged_reviews"]df.head()

SyntaxError: unterminated string literal (detected at line 15) (ipython-input-1893757017.py, line 15)